micronaut:
  application:
    name: stationService
  server:
    port: 8183
  data:
    mongodb:
      create-collections: true
rabbitmq:
  uri: amqp://${RABBITMQ_HOST}:5672
  username: "guest"
  password: "guest"
mongodb:
  uri: mongodb://root:example@${MONGODB_HOST}:27017/order?authSource=admin
